version: "3.8"
services:
  database:
    container_name: recipes-database
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
